# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb37ff543de3f1a90711cd60e6126088925387fc295f2eac0483107792cb0fd931063dade300ebd880f546077fbff10204f846a60a5ae13c3832a4d878b4fb06

test:
  secret_key_base: 3c117141d8958cbe296c554533a56d90227e02b922c74ac883267bdbe1b8016f46dbe5f96ee75455011764d677f45d7ff615bf0b6f24ed3a43eeadfc05a51d42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
